"""fix emaill to email

Revision ID: 353686fb5e03
Revises: cf843ea634f2
Create Date: 2026-07-02 12:48:01.253813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353686fb5e03'
down_revision: Union[str, Sequence[str], None] = 'cf843ea634f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('Users', 'emaill')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('emaill', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'email')
    # ### end Alembic commands ###
